framework:
    mailer:
        dsn: '%env(MAILER_DSN)%'
        envelope:
            sender: 'ensemble@coworking-hahnheim.de'
        headers:
            From: 'Ensemble Coworking Hahnheim <ensemble@coworking-hahnheim.de>'