framework:
    mailer:
        dsn: '%env(MAILER_DSN)%'
        envelope:
            sender: 'office@coworking-hahnheim.de'
        headers:
            From: 'Ensemble Coworking Hahnheim <office@coworking-hahnheim.de>'